### PR TITLE
CharCount / Zone Post Tracker Feature

### PR DESCRIPTION
**Pull request by allquixotic**
This new feature of pChat adds some optional but useful information to the top center position of the chat window header (the row of buttons at the top of the chat window).

I already have a popular addon called CharCount that supports one of the two features of this code, the "char count" (which displays the number of characters currently typed in the chat bar so you know when you're about to hit the limit of 350 chars).

This code includes the CharCount code, and extends the CharCount label to add a second feature: it displays the timestamp when you last posted a message to zone chat. It resets each time you change zone.

That might seem awfully specific, but it is common for people to post announcements (like guild recruitment, or notification about community events) to zone chat, and it's easy to lose track of whether you have posted in the current zone or not.

People in my guild desire these features. The reason I'm asking to merge it into pChat is that pChat has the canonical `CHAT_ROUTER:RegisterMessageFormatter` implementation, and I used the ChatHandler to detect when the user sends a message, for the new feature I added.

Here are some screenshots of the new stuff:

Settings:

image

Tooltips:

image

image

Example of both features enabled:

image

Wider view:

image

I am `@Coorbin` in ESO for the purposes of giving credit (if desired) and/or directing users to me for tech support. I worked with you a year ago on integrating ChatMentions and I appreciate that very much.

### CODE REVIEW

**Comment by Baertram** [comment]
Hey Sean, thanks for the feature additions. Just a few questions:

-How does the "zone chat timestamp" recognize zone chat was used? Is it using some code in the "message was send chat handler" so that every send message to zone chat is recognized via the CHAT_CHANNEL_ZONE constant? Or is it some other hacky way detectin /zone or /z entries in the chat editbox (I do not hope so :) )

-Is the position of the charcount and last zone chat movable/changeable on the UI? I know a lot users use several addons adding buttons to the chat window. So either it should be able to detect the most right button (vanilla UI is notifications number) and anchor right to it, or there should be given any way to move it on the x axis imo.

**Comment by allquixotic** [comment]
> Hey Sean, thanks for the feature additions. Just a few questions:
> 
> -How does the "zone chat timestamp" recognize zone chat was used? Is it using some code in the "message was send chat handler" so that every send message to zone chat is recognized via the CHAT_CHANNEL_ZONE constant? Or is it some other hacky way detectin /zone or /z entries in the chat editbox (I do not hope so :) )

It hooks into the "main" chat handler in ChatHandlers.lua. It compares the channelId to `CHAT_CHANNEL_ZONE` and compares the `fromClean` (the player's character name with the `^Mx` junk removed) against `pChat.pChatData.localPlayer` which is defined in pChat.lua as `GetUnitName("player")`.

So it isn't hacky in my opinion - it does it the way you seemed to think it should be.

> 
> -What time format is it using as I can see the "am" here in your example. Does it use os.time to format the timestamp and thus uses client time format properly or is it always using am/pm time?

It uses `pChat.CreateTimestamp(GetTimeString())` so if the user sets a custom timestamp format for the chat messages, it will use that custom timestamp for the header as well.

> 
> -Is the position of the charcount and last zone chat movable/changeable on the UI? I know a lot users use several addons adding buttons to the chat window. So either it should be able to detect the most right button (vanilla UI is notifications number) and anchor right to it, or there should be given any way to move it on the x axis imo.

The position is not changeable; it currently anchors to the center of the window using `control:SetAnchor(CENTER, ZO_ChatWindow, TOP, 0, 30)` 

If the user has so many buttons that there isn't space for the CharCount label, they can either make their chat window bigger, or remove some addons. I could add a feature to anchor it to the left (or right) of the window and let the user set the "x" if you want that added.

**Comment by Baertram** [comment]
I've prepared the German translations, please add them to the de.lua file within your pull request:
`
-- Coorbin20211222
-- Coorbin20211222
	-- CharCount settings strings
	PCHAT_CHARCOUNTH = "Chat Fenster Kopfbereich",
	PCHAT_CHARCOUNT_ENABLE_CHECKBOX_NAME = "Zeige Anzahl getippter Zeichen",
	PCHAT_CHARCOUNT_ENABLE_CHECKBOX_TOOLTIP = "Zeigt die Anzahl der aktuell getippten Zeichen des Text Eingabefeldes des Chats an, sowie die maximalen 350 Zeichen. Dies wird in der Kopfzeile des Chat Fensters angezeigt.",
	PCHAT_CHARCOUNT_ZONE_POST_TRACKER_NAME = "Zeige letzten ausgehenden Zonen-Chat Zeitpunkt",
	PCHAT_CHARCOUNT_ZONE_POST_TRACKER_TOOLTIP = "Zeigt den Zeitpunkt der letzten ausgehenden (gesendeten) Zonen Chat Nachricht an (in der aktuellen Zone). Der Zeitpunkt wird zurückgesetzt, wenn du die Zone wechselst. Dies kann hilfreich sein wenn man Werbung oder Ankündigugen in mehreren Zonen versenden möchte. Dies wird in der Kopfzeile des Chat Fensters angezeigt."
`

**Comment by allquixotic** [comment]
German translations pushed to my branch in the PR.

**Comment by Baertram** [comment]
> > Hey Sean, thanks for the feature additions. Just a few questions:
> > -How does the "zone chat timestamp" recognize zone chat was used? Is it using some code in the "message was send chat handler" so that every send message to zone chat is recognized via the CHAT_CHANNEL_ZONE constant? Or is it some other hacky way detectin /zone or /z entries in the chat editbox (I do not hope so :) )
> 
> It hooks into the "main" chat handler in ChatHandlers.lua. It compares the channelId to `CHAT_CHANNEL_ZONE` and compares the `fromClean` (the player's character name with the `^Mx` junk removed) against `pChat.pChatData.localPlayer` which is defined in pChat.lua as `GetUnitName("player")`.
> 
> So it isn't hacky in my opinion - it does it the way you seemed to think it should be.
> 
> > -What time format is it using as I can see the "am" here in your example. Does it use os.time to format the timestamp and thus uses client time format properly or is it always using am/pm time?
> 
> It uses `pChat.CreateTimestamp(GetTimeString())` so if the user sets a custom timestamp format for the chat messages, it will use that custom timestamp for the header as well.
> 
> > -Is the position of the charcount and last zone chat movable/changeable on the UI? I know a lot users use several addons adding buttons to the chat window. So either it should be able to detect the most right button (vanilla UI is notifications number) and anchor right to it, or there should be given any way to move it on the x axis imo.
> 
> The position is not changeable; it currently anchors to the center of the window using `control:SetAnchor(CENTER, ZO_ChatWindow, TOP, 0, 30)`
> 
> If the user has so many buttons that there isn't space for the CharCount label, they can either make their chat window bigger, or remove some addons. I could add a feature to anchor it to the left (or right) of the window and let the user set the "x" if you want that added.

Thanks for the clarification. All okay with me.
About the extra settings for the position: I guess the center is alright. If anyone needs more options I'll might bet back to you ;-)

One more question:
The last zone posted timestamp resets as zone get's switched. Is it keeping track of last time you posted in the zone "before" somehow or is it just 1 variable for all zones? I'm asking as I thought it would keep track if I have been at the zone before already, so keeps it per zone. But your description text at the settings says it will reset on each zone change.

**Comment by allquixotic** [comment]
> One more question: The last zone posted timestamp resets as zone get's switched. Is it keeping track of last time you posted in the zone "before" somehow or is it just 1 variable for all zones? I'm asking as I thought it would keep track if I have been at the zone before already, so keeps it per zone. But your description text at the settings says it will reset on each zone change.

It registers an event handler for `EVENT_PLAYER_ACTIVATED` (using the handler identifier `pChat.charCount` to avoid conflicting with pChat's original `EVENT_PLAYER_ACTIVATED` handler).

Basically, it treats an `EVENT_PLAYER_ACTIVATED` trigger as a reset of the "last post" state by clearing the string that keeps track of it. 

For those of us who recruit, I think it is easier visually to just _not display_ the timestamp at all when you change zone, so you can just glance at the top of the chat window very quickly, to see if you have posted in this zone yet. It helps avoid "double posts" (which can annoy people who keep zone chat on to help others, etc.)

It would not be difficult to extend the code to keep a table of zone ID / timestamp, and display the current timestamp. However, because this is something that would make the addon less ergonomic to use for my use case, I would gate this behind a new feature checkbox in the settings. Something like, "remember zone timestamps after changing map".

**Comment by Baertram** [comment]
> > One more question: The last zone posted timestamp resets as zone get's switched. Is it keeping track of last time you posted in the zone "before" somehow or is it just 1 variable for all zones? I'm asking as I thought it would keep track if I have been at the zone before already, so keeps it per zone. But your description text at the settings says it will reset on each zone change.
> 
> It registers an event handler for `EVENT_PLAYER_ACTIVATED` (using the handler identifier `pChat.charCount` to avoid conflicting with pChat's original `EVENT_PLAYER_ACTIVATED` handler).
> 
> Basically, it treats an `EVENT_PLAYER_ACTIVATED` trigger as a reset of the "last post" state by clearing the string that keeps track of it.
> 
> For those of us who recruit, I think it is easier visually to just _not display_ the timestamp at all when you change zone, so you can just glance at the top of the chat window very quickly, to see if you have posted in this zone yet. It helps avoid "double posts" (which can annoy people who keep zone chat on to help others, etc.)
> 
> It would not be difficult to extend the code to keep a table of zone ID / timestamp, and display the current timestamp. However, because this is something that would make the addon less ergonomic to use for my use case, I would gate this behind a new feature checkbox in the settings. Something like, "remember zone timestamps after changing map".

Okay, understood. I thought it was meant to help keep tarck where you have been already to post zone messages and thus I thought it would remember the timestamp for each zone. No problem , I just have to adopt the German translations a bit then.
I'll merge your request now and test it a bit, thanks for the features! I have to remove a debug line left over in last update so it's good to have a proper update with more content :-p

**Comment by allquixotic** [comment]
Thanks, Baertram. Have a great holiday, and don't hesitate to reach out to me here on GitHub or at smcnam@gmail.com if you have any questions about the code I've contributed to pChat.

**Comment by Baertram** [comment]
The same to you, Merry Christmas 🎄

**Pull request merged**
